[project]
name = "transfer-room-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bif-code",
    "streamlit==1.44.0"

]

[tool.uv.sources]
bif-code = { git = "https://github.com/brondby-if/sport-bif-code"}
