name: Deploy to Docker Hub

on:
  push:
    branches:
      - main 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t sk1295/player-updater .
          docker tag sk1295/player-updater sk1295/player-updater:latest
          docker push sk1295/player-updater:latest
