name: Deploy to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t suma1295/player-updater .

      - name: Tag Docker image
        run: docker tag suma1295/player-updater suma1295/player-updater:latest

      - name: Push Docker image to Docker Hub
        run: docker push suma1295/player-updater:latest

      - name: Log out from Docker Hub
        run: docker logout
