services:
  airflow:
    container_name: airflow_app
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/app/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mssql+pyodbc://sa:StrongPassword123@host.docker.internal:1433/airflowdb?driver=ODBC+Driver+17+for+SQL+Server

      - PYTHONPATH=/app:/app/airflow:/app/python_code
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password airflow123 &&
        airflow scheduler & airflow webserver -p 8080
      "
