version: "3.8"

services:
  player_updater:
    container_name: player-updater-container 
    build: .
    restart: always
    ports:
      - "8501:8501"  
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1 